name: Develop

on:
  push:
    branches:
      - develop

jobs:
  test-memory-2026:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Vérifier tous les fichiers .JPG
        shell: bash
        run: |
          for img in $(find . -type f -name "*.jpg"); do
            file "$img"
          done

  build-memory-2026:
    runs-on: self-hosted
    needs: test-memory-2026
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Dockerhub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        shell: bash
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/memory-2026 .
          docker images
